### ISSUE TITLE
what will the udp-tunnel-server do after it listens on <listen-port>?

### ISSUE THREAD

**Issue by luckypoem** [thbaumbach/node-udp-tunnel-cli#1]
udp-tunnel-server <listen-port> <tunnel-port>

what will the udp-tunnel-server do after it listens on <listen-port>? 
i don't understand.
forwatd the traffic to some http proxy app such as squid on the server?

**Comment by thbaumbach** [comment]
Hi,

sorry for the **very late** reply. The server is basically a proxy for any UDP data. This has nothing to do with HTTP or other TCP data at all.

There are two different commands in this package: `udp-tunnel-server` and `udp-tunnel-client`

Both are parts of the proxy. One is the "public" part which acts as server for all incoming traffic and transfers that traffic to the client part which routes all data to a third-party server.

Usage example: serve a UDP server behind a firewall without additional firewall rules or a mediator

I hope that helped.

**Comment by thbaumbach** [comment]
Some additional information: (I think I've missed some details)

After starting `udp-tunnel-server` the server will wait until a connection will be setup through the   `<tunnel-port>` initiated by `udp-tunnel-client`.

Once this has happened the server will route all incoming traffic on `<listen-port>` through the tunnel to the client-server, which initiated the tunnel connection beforehand.

**Comment by luckypoem** [comment]
in china,there is a gfw(great firewall of china),so could u develop a  node-tcp-tunnel-cli?
i want to utilize node-tcp-tunnel-cli to make a web browser to cross the GFW.

**Comment by thbaumbach** [comment]
UDP is not used for HTTP(S) traffic
